#!/bin/bash

# a small script to show lvmcache statistics
# license - BSD
# usage:
#   lvmcache-stats vg0/lv_data

# use strict mode
set -o errexit
set -o pipefail
set -o nounset

FIELDS=$(cat <<EOF
start
end
segment_type
md_block_size
md_utilization
cache_block_size
cache_utilization
read_hits
read_misses
write_hits
write_misses
demotions
promotions
dirty
features
EOF
)
FIELD_COUNT=$(echo "$FIELDS" | wc -l)

function extract_stat()
{
    echo "$1" | awk "/$2/ { print \$2 }"
}

function percent()
{
    awk "BEGIN { printf \"%.2f%%\", 100*$1/$2 }"
}

function insert_after()
{
    awk "// { print } ; /$1/ { print \"\n$2 $3\" }"
}

CACHE_ID=`echo "$1" | sed 's/-/--/' | tr / -`
CACHE_STATS=$(paste <(echo "$FIELDS") <(dmsetup status | grep "${CACHE_ID}:" | sed -r -e 's/.*: (.*)/\1/' | tr ' ' '\n' | head -n${FIELD_COUNT}))

# calculate cache hit percentage
READ_HITS=$(extract_stat "$CACHE_STATS" read_hits)
READ_MISSES=$(extract_stat "$CACHE_STATS" read_misses)
READ_HIT_RATIO=$(percent $READ_HITS $(($READ_MISSES+$READ_HITS)))

WRITE_HITS=$(extract_stat "$CACHE_STATS" write_hits)
WRITE_MISSES=$(extract_stat "$CACHE_STATS" write_misses)
WRITE_HIT_RATIO=$(percent $WRITE_HITS $(($WRITE_MISSES+$WRITE_HITS)))

echo "$CACHE_STATS" | \
    insert_after read_misses read_hit_ratio "$READ_HIT_RATIO" | \
    insert_after write_misses write_hit_ratio "$WRITE_HIT_RATIO" | \
    column -t
